ingress:
  hostname: openenzymedb.platform.moleculemaker.org
  extraHosts:
  - openenzymedb.frontend.mmli1.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "alphasynthesis-openenzymedb-prod-domain-redirect@kubernetescrd"

controller:
  image: moleculemaker/openenzymedb-frontend:main

config:
  hostname: "https://mmli.fastapi.mmli1.ncsa.illinois.edu"
  basePath: ""
  signInUrl: "https://auth.platform.moleculemaker.org/oauth2/start?rd=https%3A%2F%2Fopenenzymedb.platform.moleculemaker.org%2Fconfiguration"
  signOutUrl: "https://auth.platform.moleculemaker.org/oauth2/sign_out?rd=https%3A%2F%2Fopenenzymedb.platform.moleculemaker.org%2Fconfiguration"
  userInfoUrl: "https://auth.platform.moleculemaker.org/oauth2/userinfo"
  frontendOnly: "false"

extraDeploy:
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    name: openenzymedb-prod-domain-redirect
    namespace: alphasynthesis
  spec:
    redirectRegex:
      regex: "^https://openenzymedb.frontend.mmli1.ncsa.illinois.edu/(.*)"
      replacement: "https://openenzymedb.platform.moleculemaker.org/${1}"
      permanent: true
