ingress:
  hostname: frontend.staging.openenzymedb.mmli2.ncsa.illinois.edu
  extraHosts:
  - frontend.staging.openenzymedb.mmli1.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "staging-oed-staging-domain-redirect@kubernetescrd"

controller:
  image: moleculemaker/openenzymedb-frontend:staging

config:
  hostname: "https://mmli.fastapi.staging.mmli2.ncsa.illinois.edu"
  basePath: ""
  signInUrl: "https://auth.openenzymedb.mmli2.ncsa.illinois.edu/oauth2/start?rd=https%3A%2F%2Ffrontend.staging.openenzymedb.mmli2.ncsa.illinois.edu%2Fconfiguration"
  signOutUrl: "https://auth.openenzymedb.mmli2.ncsa.illinois.edu/oauth2/sign_out?rd=https%3A%2F%2Ffrontend.staging.openenzymedb.mmli2.ncsa.illinois.edu%2Fconfiguration"
  userInfoUrl: "https://auth.openenzymedb.mmli2.ncsa.illinois.edu/oauth2/userinfo"

  frontendOnly: "false"
  whitePaperUrl: ""
  visionUrl: "https://docs.google.com/document/d/17nfpqWG8N8uS4wGpNlUumwknwh7kIsKp2rZNv6TLYyk/edit?usp=sharing"
  feedbackUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfISchgT9oNHL5f0_Ev1T0BD736AakYnS4GUuJJdtA9fxF78A/viewform"
  releaseNotesUrl: "https://docs.google.com/document/d/1cNrChDPUl5jh_CfzaShBB-_Hn0JuFvMwWEEqP81vm7A/"

  molDBHostname: "https://postgrest.openenzymedb.mmli2.ncsa.illinois.edu"
  molDBBasePath: ""

extraDeploy:
# Redirect any users attempting to go to mmli1 and bring them to mmli2 instead
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    name: oed-staging-domain-redirect
    namespace: staging
  spec:
    redirectRegex:
      regex: "^https:\\/\\/frontend\\.staging\\.openenzymedb\\.mmli\\d\\.ncsa\\.illinois\\.edu(\\/.*)"
      replacement: "https://frontend.staging.openenzymedb.mmli2.ncsa.illinois.edu${1}"
      permanent: true
