ingress:
  hostname: openenzymedb.proxy.localhost
  tls: false
  annotations: {}

controller:
  image: moleculemaker/openenzymedb-frontend

config:
  hostname: "https://mmli.fastapi.staging.mmli1.ncsa.illinois.edu"
  basePath: ""
  signInUrl: "https://mmli1.ncsa.illinois.edu/oauth2/start?rd=https%3A%2F%2Fopenenzymedb.proxy.localhost%2Fconfiguration"
  signOutUrl: "https://mmli1.ncsa.illinois.edu/oauth2/sign_out?rd=https%3A%2F%2Fopenenzymedb.proxy.localhost%2Fconfiguration"
  userInfoUrl: "https://mmli1.ncsa.illinois.edu/oauth2/userinfo"

  frontendOnly: "true"
  whitePaperUrl: ""
  visionUrl: "https://docs.google.com/document/d/17nfpqWG8N8uS4wGpNlUumwknwh7kIsKp2rZNv6TLYyk/edit?usp=sharing"
  feedbackUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfISchgT9oNHL5f0_Ev1T0BD736AakYnS4GUuJJdtA9fxF78A/viewform"

  molDBHostname: "https://postgrest.openenzymedb.mmli1.ncsa.illinois.edu"
  molDBBasePath: ""
extraDeploy: []
