export * from './dataDfKcat.service';
import { DataDfKcatService } from './dataDfKcat.service';
export * from './dataDfKcatkm.service';
import { DataDfKcatkmService } from './dataDfKcatkm.service';
export * from './dataDfKm.service';
import { DataDfKmService } from './dataDfKm.service';
export * from './introspection.service';
import { IntrospectionService } from './introspection.service';
export * from './kcatEcPieChart.service';
import { KcatEcPieChartService } from './kcatEcPieChart.service';
export * from './kcatkmEcPieChart.service';
import { KcatkmEcPieChartService } from './kcatkmEcPieChart.service';
export * from './kineticSummary.service';
import { KineticSummaryService } from './kineticSummary.service';
export * from './kmEcPieChart.service';
import { KmEcPieChartService } from './kmEcPieChart.service';
export * from './table1.service';
import { Table1Service } from './table1.service';
export const APIS = [DataDfKcatService, DataDfKcatkmService, DataDfKmService, IntrospectionService, KcatEcPieChartService, KcatkmEcPieChartService, KineticSummaryService, KmEcPieChartService, Table1Service];
