/**
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * The version of the OpenAPI document: 12.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { DataDfKm } from '../model/dataDfKm';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class DataDfKmService {

    protected basePath = 'http://0.0.0.0:4000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (Array.isArray(basePath) && basePath.length > 0) {
                basePath = basePath[0];
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    // @ts-ignore
    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param ec 
     * @param substrate 
     * @param organism 
     * @param uniprot 
     * @param enzymetype 
     * @param ph 
     * @param temperature 
     * @param pubmedid 
     * @param kMVALUE 
     * @param unit 
     * @param smiles 
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public dataDfKmDelete(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any>;
    public dataDfKmDelete(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpResponse<any>>;
    public dataDfKmDelete(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpEvent<any>>;
    public dataDfKmDelete(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (ec !== undefined && ec !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>ec, 'ec');
        }
        if (substrate !== undefined && substrate !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>substrate, 'substrate');
        }
        if (organism !== undefined && organism !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>organism, 'organism');
        }
        if (uniprot !== undefined && uniprot !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>uniprot, 'uniprot');
        }
        if (enzymetype !== undefined && enzymetype !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>enzymetype, 'enzymetype');
        }
        if (ph !== undefined && ph !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>ph, 'ph');
        }
        if (temperature !== undefined && temperature !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>temperature, 'temperature');
        }
        if (pubmedid !== undefined && pubmedid !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>pubmedid, 'pubmedid');
        }
        if (kMVALUE !== undefined && kMVALUE !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>kMVALUE, 'KM VALUE');
        }
        if (unit !== undefined && unit !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>unit, 'unit');
        }
        if (smiles !== undefined && smiles !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>smiles, 'smiles');
        }

        let localVarHeaders = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            localVarHeaders = localVarHeaders.set('Prefer', String(prefer));
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/data_df_km`;
        return this.httpClient.request<any>('delete', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param ec 
     * @param substrate 
     * @param organism 
     * @param uniprot 
     * @param enzymetype 
     * @param ph 
     * @param temperature 
     * @param pubmedid 
     * @param kMVALUE 
     * @param unit 
     * @param smiles 
     * @param select Filtering Columns
     * @param order Ordering
     * @param range Limiting and Pagination
     * @param rangeUnit Limiting and Pagination
     * @param offset Limiting and Pagination
     * @param limit Limiting and Pagination
     * @param prefer Preference
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public dataDfKmGet(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/vnd.pgrst.object+json;nulls&#x3D;stripped' | 'application/vnd.pgrst.object+json' | 'text/csv', context?: HttpContext}): Observable<Array<DataDfKm>>;
    public dataDfKmGet(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/vnd.pgrst.object+json;nulls&#x3D;stripped' | 'application/vnd.pgrst.object+json' | 'text/csv', context?: HttpContext}): Observable<HttpResponse<Array<DataDfKm>>>;
    public dataDfKmGet(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/vnd.pgrst.object+json;nulls&#x3D;stripped' | 'application/vnd.pgrst.object+json' | 'text/csv', context?: HttpContext}): Observable<HttpEvent<Array<DataDfKm>>>;
    public dataDfKmGet(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, select?: string, order?: string, range?: string, rangeUnit?: string, offset?: string, limit?: string, prefer?: 'count=none', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/vnd.pgrst.object+json;nulls&#x3D;stripped' | 'application/vnd.pgrst.object+json' | 'text/csv', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (ec !== undefined && ec !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>ec, 'ec');
        }
        if (substrate !== undefined && substrate !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>substrate, 'substrate');
        }
        if (organism !== undefined && organism !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>organism, 'organism');
        }
        if (uniprot !== undefined && uniprot !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>uniprot, 'uniprot');
        }
        if (enzymetype !== undefined && enzymetype !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>enzymetype, 'enzymetype');
        }
        if (ph !== undefined && ph !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>ph, 'ph');
        }
        if (temperature !== undefined && temperature !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>temperature, 'temperature');
        }
        if (pubmedid !== undefined && pubmedid !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>pubmedid, 'pubmedid');
        }
        if (kMVALUE !== undefined && kMVALUE !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>kMVALUE, 'KM VALUE');
        }
        if (unit !== undefined && unit !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>unit, 'unit');
        }
        if (smiles !== undefined && smiles !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>smiles, 'smiles');
        }
        if (select !== undefined && select !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>select, 'select');
        }
        if (order !== undefined && order !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>order, 'order');
        }
        if (offset !== undefined && offset !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>offset, 'offset');
        }
        if (limit !== undefined && limit !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>limit, 'limit');
        }

        let localVarHeaders = this.defaultHeaders;
        if (range !== undefined && range !== null) {
            localVarHeaders = localVarHeaders.set('Range', String(range));
        }
        if (rangeUnit !== undefined && rangeUnit !== null) {
            localVarHeaders = localVarHeaders.set('Range-Unit', String(rangeUnit));
        }
        if (prefer !== undefined && prefer !== null) {
            localVarHeaders = localVarHeaders.set('Prefer', String(prefer));
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json',
                'application/vnd.pgrst.object+json;nulls=stripped',
                'application/vnd.pgrst.object+json',
                'text/csv'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/data_df_km`;
        return this.httpClient.request<Array<DataDfKm>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param ec 
     * @param substrate 
     * @param organism 
     * @param uniprot 
     * @param enzymetype 
     * @param ph 
     * @param temperature 
     * @param pubmedid 
     * @param kMVALUE 
     * @param unit 
     * @param smiles 
     * @param prefer Preference
     * @param dataDfKm data_df_km
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public dataDfKmPatch(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', dataDfKm?: DataDfKm, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any>;
    public dataDfKmPatch(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', dataDfKm?: DataDfKm, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpResponse<any>>;
    public dataDfKmPatch(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', dataDfKm?: DataDfKm, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpEvent<any>>;
    public dataDfKmPatch(ec?: string, substrate?: string, organism?: string, uniprot?: string, enzymetype?: string, ph?: string, temperature?: string, pubmedid?: string, kMVALUE?: string, unit?: string, smiles?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none', dataDfKm?: DataDfKm, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (ec !== undefined && ec !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>ec, 'ec');
        }
        if (substrate !== undefined && substrate !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>substrate, 'substrate');
        }
        if (organism !== undefined && organism !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>organism, 'organism');
        }
        if (uniprot !== undefined && uniprot !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>uniprot, 'uniprot');
        }
        if (enzymetype !== undefined && enzymetype !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>enzymetype, 'enzymetype');
        }
        if (ph !== undefined && ph !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>ph, 'ph');
        }
        if (temperature !== undefined && temperature !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>temperature, 'temperature');
        }
        if (pubmedid !== undefined && pubmedid !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>pubmedid, 'pubmedid');
        }
        if (kMVALUE !== undefined && kMVALUE !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>kMVALUE, 'KM VALUE');
        }
        if (unit !== undefined && unit !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>unit, 'unit');
        }
        if (smiles !== undefined && smiles !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>smiles, 'smiles');
        }

        let localVarHeaders = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            localVarHeaders = localVarHeaders.set('Prefer', String(prefer));
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json;nulls=stripped',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/data_df_km`;
        return this.httpClient.request<any>('patch', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: dataDfKm,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param select Filtering Columns
     * @param prefer Preference
     * @param dataDfKm data_df_km
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public dataDfKmPost(select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none' | 'resolution=ignore-duplicates' | 'resolution=merge-duplicates', dataDfKm?: DataDfKm, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any>;
    public dataDfKmPost(select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none' | 'resolution=ignore-duplicates' | 'resolution=merge-duplicates', dataDfKm?: DataDfKm, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpResponse<any>>;
    public dataDfKmPost(select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none' | 'resolution=ignore-duplicates' | 'resolution=merge-duplicates', dataDfKm?: DataDfKm, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpEvent<any>>;
    public dataDfKmPost(select?: string, prefer?: 'return=representation' | 'return=minimal' | 'return=none' | 'resolution=ignore-duplicates' | 'resolution=merge-duplicates', dataDfKm?: DataDfKm, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (select !== undefined && select !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>select, 'select');
        }

        let localVarHeaders = this.defaultHeaders;
        if (prefer !== undefined && prefer !== null) {
            localVarHeaders = localVarHeaders.set('Prefer', String(prefer));
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/vnd.pgrst.object+json;nulls=stripped',
            'application/vnd.pgrst.object+json',
            'text/csv'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/data_df_km`;
        return this.httpClient.request<any>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: dataDfKm,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
