/**
 * PostgREST API
 * This is a dynamic API generated by PostgREST
 *
 * The version of the OpenAPI document: 12.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KineticSummary { 
    metric?: string;
    kcat_dataset?: number;
    km_dataset?: number;
    kcat_km_dataset?: number;
}

